import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

const noto_serif_bengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      data-theme ='light'
      className={`${noto_serif_bengali.className}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <main className="flex-grow">
          {children}
        </main>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
